### ISSUE TITLE
Errors for wrong URLs

### ISSUE THREAD

**Issue by gacha** [atlassian-labs/connect-security-req-tester#15]
Hi @seanmarpo,
I started to test our app and had few strange errors in the resulting report. There is an excerpt of our plugin configuration:
```json
"postInstallPage":{"key":"getting-started","url":"/atlassian-connect/eazybi-jira/getting_started?user_is_admin={condition.user_is_admin}","name":{"value":"Get started"}}
```
the PATH for the post install page is `/atlassian-connect/eazybi-jira/getting_started` but in requirement 5 we got an error for a slightly different PATH: `/atlassian-connect/eazybi-jira/gettingstarted?useris_admin=true`, the underscore is missing.

There is another similar issue:
```json
"jiraDashboardItems":[{"key":"report-gadget","name":{"value":"eazyBI report"},"description":{"value":"Embed selected eazyBI report."},"url":"/atlassian-connect/eazybi-jira/jira_dashboard_items/report?jira_dashboard_id={dashboard.id}\u0026jira_dashboard_item_id={dashboardItem.id}\u0026view_type={dashboardItem.viewType}\u0026user_is_admin={condition.user_is_admin}","configurable":false,"thumbnailUrl":"/images/eazybi_gadget.png"},{"key":"dashboard-gadget","name":{"value":"eazyBI dashboard"},"description":{"value":"Embed selected eazyBI dashboard."},"url":"/atlassian-connect/eazybi-jira/jira_dashboard_items/dashboard?jira_dashboard_id={dashboard.id}\u0026jira_dashboard_item_id={dashboardItem.id}\u0026view_type={dashboardItem.viewType}\u0026user_is_admin={condition.user_is_admin}","configurable":false,"thumbnailUrl":"/images/eazybi_gadget.png"}]
```
so the PATH should be `/atlassian-connect/eazybi-jira/jira_dashboard_items/dashboard`, but we got error on this PATH `/atlassian-connect/eazybi-jira/jiradashboarditems/report?jiradashboardid=test&userisadmin=true`

One more thing, I see that some pages which are expecting GET requests are receiving POST requests instead and vice-versa - is this intended? This results in 404 and with different headers.

Thanks for your effort.

**Comment by seanmarpo** [comment]
Hi @gacha, can you include your connect app's descriptor URL? Once I have that, I'll check it for you.

**Comment by gacha** [comment]
@seanmarpo sure, https://aod.eazybi.com/atlassian-connect/eazybi-jira/atlassian-connect.json

**Comment by seanmarpo** [comment]
Thanks for sending that over.

You are seeing a bug in the markdown parser which converts surrounding underscores to _italics_. The link in the HTML report is still correct, but it is displayed wrong.

You can test this by right-clicking, and choosing "Copy Link Address". The resulting link is correct.

**Comment by gacha** [comment]
Ok, now this is clear.

One more thing, I see that some pages which are expecting POST requests like enabled/disabled/webhooks are receiving GET requests instead, and vice-versa - is this intended? This results in 404 as those are completely different routes.

Thanks.

**Comment by seanmarpo** [comment]
The latest code should fix the HTML reporting issue you were experiencing.

As part of CSRT's analysis, we attempt to probe all the available endpoints that we find. This means, submitting a GET, POST, and a few additional requests with fake authentication tokens. It allows us to validate that your app is doing proper authentication checks.
