### ISSUE TITLE
fire module dependency

### ISSUE THREAD

**Issue by thorseriph** [atlassian-labs/connect-security-req-tester#24]
I had an issue with running this python script initally and got the following error.
`ModuleNotFoundError: No module named 'fire'`
(pip3 install fire did not work)

This can be solved by installing fire using pipenv
`python3 -m pipenv install fire`

may be worth to add as documentation

**Comment by james-dellow** [comment]
I also added a comment here related to this https://community.developer.atlassian.com/t/upcoming-new-security-scanning-activities-on-marketplace-apps/43715/15?u=james.dellow

**Comment by seanmarpo** [comment]
Hi there - This is technically called out in the README in a minor link above the python section, but I do agree the docs need some love. We've been scrambling to add features that the docs have take an unfortunate backseat.

I'll file a public issue, so it's off my internal to-do list.
