### ISSUE TITLE
Static files with "cacheable": true fails requirement 5

### ISSUE THREAD

**Issue by james-dellow** [atlassian-labs/connect-security-req-tester#25]
Static files with "cacheable": true are failing requirement 5.

**Comment by seanmarpo** [comment]
@james-dellow, thanks for taking the time to help us test CSRT.

If you could kindly provide the URL to descriptor or app-key for an app that is exhibiting this failure, I'm happy to look into it and get it resolved.

**Comment by james-dellow** [comment]
Have a look at app-key: au.com.chieftech.intranet-news
BTW there are 3 static pages but only 1 is flagged as cacheable currently. I'll look to move all 3 to this configuration if this can be resolved. One is using a context parameter, but I have that working in dev now using AP.context instead.
