### ISSUE TITLE
False warnings for Heroku apps

### ISSUE THREAD

**Issue by unuseless** [atlassian-labs/connect-security-req-tester#35]
The security tester checks if an app is hosted on a Heroku domain to whitelist Heroku apps with regard to TLS testing.

However some apps are hosted on Heroku, using a custom domain.  These apps are not whitelisted.  In principle this can be checked through a DNS query, and see if the domain points through a CNAME record to a Heroku domain.

**Comment by seanmarpo** [comment]
Thanks for the heads up -- I figured that logic wasn't bulletproof.

Could you please include an app key, url to descriptor, or marketplace link to your app? I'll take a look at it for you.

**Comment by unuseless** [comment]
@seanmarpo information requested is in a CDAC message.

**Comment by seanmarpo** [comment]
Got it, thanks. Working on a fix now.
