### ISSUE TITLE
Warning for blueprint.xml

### ISSUE THREAD

**Issue by unuseless** [atlassian-labs/connect-security-req-tester#36]
When scanning we get a warning that we don't check for authentication on our `blueprints/blueprint.xml` endpoint.  However enabling authentication on our end is a problem, as it seems Confluence does not send the authentication header when accessing this endpoint.  If we enable authentication we get the following error from ACE:
`{ ctx: {} } Authentication verification error (401):  Could not find authentication data on request`

**Comment by seanmarpo** [comment]
I thought I had accounted for this, as I have a local test app that exposes a page template via a `blueprint.xml`.

Could you please include an app key, url to your app's descriptor, or a marketplace link for an example app that fails this check? I'll take a look at it for you.

**Comment by unuseless** [comment]
@seanmarpo information requested is in a CDAC message.
