### ISSUE TITLE
Receiving /install lifecycle requests with null content type

### ISSUE THREAD

**Issue by pelizza** [atlassian-labs/connect-security-req-tester#45]
**Describe the bug**
We are receiving 12 `/install` requests every day where the agent is set as `CSRT (github.com/atlassian-labs/connect-security-req-tester)` but the `content-type` of these requests is `null`. As a result, our backend is responding with an error 500.

**To Reproduce**
Send a `/install` event to Zephyr Scale without setting the content type. This will cause Zephyr Scale to respond with an error 500.

**Expected behavior**
The `/install` requests come with `content-type` set as `application/json` 

**Marketplace App Information**
* com.kanoah.test-manager
* https://marketplace.atlassian.com/apps/1213259/zephyr-scale-test-management-for-jira
* Zephyr Scale - Test Management for Jira

**Comment by seanmarpo** [comment]
Thanks, we definitely do not send a JSON content-type during lifecycle requests. I'll get this prioritized for fixing.
