### ISSUE TITLE
ACE crashes on security sweep

### ISSUE THREAD

**Issue by hitsthings** [atlassian-labs/connect-security-req-tester#67]
**Describe the bug**
This is a great service, thanks. But it causes your own library, ACE, to crash an Express server.

**To Reproduce**
Set up a Node instance with ACE and set `expressErrorHandling: true,`. Hit the /install or /uninstall endpoint with the service that identifies itself as this repo.

**Expected behavior**
ACE doesn't cause my app to crash. I created a PR for that at https://bitbucket.org/atlassian/atlassian-connect-express/pull-requests/393 which has been ignored.

For anyone else hitting this,  you can set `req.context` to an empty object before running verify and it will start failing with 401s instead of crashing. E.g.

```ts
const preventACEBug = (req: Request, res: Response, next: () => void) => {
    (req as any).context = {};
    next();
  };
  routes.post('/installed', preventACEBug, aceAddon.verifyInstallation(), aceAddon.postInstallation());
```

**Comment by seanmarpo** [comment]
Hey there! I've alerted the team that maintains ACE about your PR. Unfortunately, as you can imagine, there's not a whole lot that we can do. I'll leave this open until I've heard some kind of feedback from them. 

Appreciate your understanding.

**Comment by hitsthings** [comment]
Thanks Sean!

**Comment by seanmarpo** [comment]
This is being reviewed by the ecosystem platform team. Gonna close this out over here.
